fix: resolved npm audit issues
contentstack/datasync-content-store-filesystem pull request #5
Opened 2022-09-20 15:55 UTC by vkalta

2022-10-28 12:48 UTC, netrajpatel requested changes
@vkalta Update package versions

2022-10-28 15:50 UTC, aravindbuilt approved these changes

2022-10-30 20:48 UTC, vkalta commented
> fix: updated version

Done @netrajpatel .

2022-10-31 10:15 UTC, netrajpatel approved these changes

2022-10-31 12:37 UTC, netrajpatel approved these changes

2022-10-31 12:53 UTC, merged